version: '3.9'

services:
  postit-db:
    image: mysql:8.0
    command: [ "--default-authentication-plugin=mysql_native_password", "--sql_mode=NO_ENGINE_SUBSTITUTION" ]
    volumes:
      - postit-db-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "postit_db"

volumes:
  postit-db-data:
    driver_opts:
      type: none
      device: ${HOME}/docker/volumes/postit-db-data
      o: bind